import json
import logging
import uuid
import datetime

import numpy as np
import redis
from sklearn.metrics.pairwise import cosine_similarity
from langsmith import traceable

logger = logging.getLogger(__name__)

# ── Threshold for a semantic cache hit ──────────────────────────────────────
CACHE_SIMILARITY_THRESHOLD = 0.8
CACHE_TTL_SECONDS = 3600


def _is_available(redis_client: redis.Redis) -> bool:
    """Return True if the given Redis client can be reached."""
    try:
        return redis_client.ping()
    except (redis.exceptions.ConnectionError, redis.exceptions.TimeoutError, redis.exceptions.RedisError):
        return False


@traceable(run_type="retriever", name="Semantic_Cache_Match")
def semantic_cache_match(
    redis_client: redis.Redis,
    user_query_embedding: list,
    session_id: str,
    threshold: float = CACHE_SIMILARITY_THRESHOLD,
):
    """Look up the best matching cached answer for the given query embedding.

    Args:
        redis_client: Shared Redis connection from app state.
        user_query_embedding: Embedding vector for the current query.
        threshold: Minimum cosine similarity to count as a hit.

    Returns:
        Tuple of (cached_context, cached_chunks) on a hit, else None.
    """
    if not _is_available(redis_client):
        return None

    try:
        keys = redis_client.scan_iter(f"semantic_cache:{session_id}:*")
        best_match = None
        highest_score = 0.0

        for key in keys:
            raw = redis_client.get(key)
            if not raw:
                continue
            data = json.loads(raw)
            cached_embedding = data["embedding"]
            cached_context = data["context"]
            cached_chunks = data.get("chunk_data", [])

            score = cosine_similarity([cached_embedding], [user_query_embedding])[0][0]

            if score > highest_score:
                highest_score = score
                best_match = (cached_context, cached_chunks)

        if highest_score >= threshold and best_match is not None:
            logger.info(f"Semantic cache hit (score={highest_score:.4f})")
            return best_match

        logger.debug("Semantic cache miss")
        return None

    except redis.exceptions.RedisError as exc:
        logger.warning(f"Redis error during cache lookup: {exc}")
        return None


def store_semantic_cache(
    redis_client: redis.Redis,
    user_query: str,
    new_query: list,
    query_embedding,
    context: str,
    session_id: str,
    chunk_data=None,
) -> bool:
    """Persist a query + its retrieved context to the semantic cache.

    Args:
        redis_client: Shared Redis connection from app state.
        user_query: Original user question.
        new_query: Expanded queries generated by multi-query.
        query_embedding: Embedding of the combined query string.
        context: Retrieved context string passed to the LLM.
        chunk_data: Scored chunk list to store alongside the context.

    Returns:
        True on success, False on failure.
    """
    if not _is_available(redis_client):
        return False

    try:
        if hasattr(query_embedding, "tolist"):
            query_embedding = query_embedding.tolist()
        if hasattr(context, "tolist"):
            context = context.tolist()
        if hasattr(chunk_data, "tolist"):
            chunk_data = chunk_data.tolist()

        data = {
            "user_query": user_query,
            "new_query": new_query,
            "embedding": query_embedding,
            "context": context,
            "chunk_data": chunk_data,
            "created_at": datetime.datetime.now().isoformat(),
        }

        key = f"semantic_cache:{session_id}:{uuid.uuid4()}"
        redis_client.set(key, json.dumps(data), ex=CACHE_TTL_SECONDS)
        logger.info(f"Semantic cache stored under {key} (TTL={CACHE_TTL_SECONDS}s)")
        return True

    except redis.exceptions.RedisError as exc:
        logger.warning(f"Redis error during cache store: {exc}")
        return False